//
// Created by jordan on 3/2/20.
//

#ifndef WORDSEARCHKATA_TESTCONSTANTS_HPP
#define WORDSEARCHKATA_TESTCONSTANTS_HPP

#define WORD_GRID_ROWS 15
#define WORDS_IN_PROVIDED_WORD_SEARCH 7

#endif //WORDSEARCHKATA_TESTCONSTANTS_HPP
